
package com.taletable.android.model.theme.official


import com.taletable.android.model.theme.*


/**
 * LIGHT THEME
 */



val palette = mutableListOf(
        ThemeColor(ColorId.Theme("white"), "#FFFFFF"),
        ThemeColor(ColorId.Theme("grey_500"), "#7F000000"),
        ThemeColor(ColorId.Theme("grey_400"), "#66000000"),
        ThemeColor(ColorId.Theme("grey_300"), "#4D000000"),
        ThemeColor(ColorId.Theme("light_grey_1"), "#FAFAFA"),
        ThemeColor(ColorId.Theme("light_grey_2"), "#F7F7F7"),
        ThemeColor(ColorId.Theme("light_grey_3"), "#F3F3F3"),
        ThemeColor(ColorId.Theme("light_grey_4"), "#EFEFEF"),
        ThemeColor(ColorId.Theme("light_grey_5"), "#EAEAEA"),
        ThemeColor(ColorId.Theme("light_grey_55"), "#E8E8E8"),
        ThemeColor(ColorId.Theme("light_grey_6"), "#E6E6E6"),
        ThemeColor(ColorId.Theme("light_grey_7"), "#E2E2E2"),
        ThemeColor(ColorId.Theme("light_grey_8"), "#DDDDDD"),
        ThemeColor(ColorId.Theme("light_grey_9"), "#D9D9D9"),
        ThemeColor(ColorId.Theme("light_grey_10"), "#D5D5D5"),
        ThemeColor(ColorId.Theme("light_grey_11"), "#D1D1D1"),
        ThemeColor(ColorId.Theme("light_grey_12"), "#CCCCCC"),
        ThemeColor(ColorId.Theme("light_grey_13"), "#C8C8C8"),
        ThemeColor(ColorId.Theme("light_grey_14"), "#C4C4C4"),
        ThemeColor(ColorId.Theme("light_grey_15"), "#A9A9A9"),
        ThemeColor(ColorId.Theme("light_grey_16"), "#A5A5A5"),
        ThemeColor(ColorId.Theme("light_grey_17"), "#A1A1A1"),
        ThemeColor(ColorId.Theme("light_grey_18"), "#9C9C9C"),
        ThemeColor(ColorId.Theme("light_grey_19"), "#969696"),
        ThemeColor(ColorId.Theme("light_grey_20"), "#919191"),
        ThemeColor(ColorId.Theme("light_blue_grey_1"), "#F9FCFF"),
        ThemeColor(ColorId.Theme("light_blue_grey_2"), "#F4F7FA"),
        ThemeColor(ColorId.Theme("light_blue_grey_3"), "#F1F4F7"),
        ThemeColor(ColorId.Theme("light_blue_grey_4"), "#EEF0F3"),
        ThemeColor(ColorId.Theme("light_blue_grey_5"), "#E9ECEF"),
        ThemeColor(ColorId.Theme("light_blue_grey_6"), "#E4E7EA"),
        ThemeColor(ColorId.Theme("light_blue_grey_7"), "#E0E3EB"),
        ThemeColor(ColorId.Theme("light_blue_grey_8"), "#DCDFE2"),
        ThemeColor(ColorId.Theme("light_blue_grey_9"), "#D7DCDF"),
        ThemeColor(ColorId.Theme("light_blue_grey_10"), "#D3D6D9"),
        ThemeColor(ColorId.Theme("light_blue_grey_11"), "#CFD2D5"),
        ThemeColor(ColorId.Theme("light_blue_grey_12"), "#CBCED1"),
        ThemeColor(ColorId.Theme("light_blue_grey_13"), "#C6C9CC"),
        ThemeColor(ColorId.Theme("light_blue_grey_14"), "#C2C5CD"),
        ThemeColor(ColorId.Theme("light_blue_grey_15"), "#BEC1C4"),
        ThemeColor(ColorId.Theme("light_blue_grey_16"), "#A3A6A9"),
        ThemeColor(ColorId.Theme("light_blue_grey_17"), "#9FA2A5"),
        ThemeColor(ColorId.Theme("light_blue_grey_18"), "#9A9DA1"),
        ThemeColor(ColorId.Theme("light_blue_grey_19"), "#96999C"),
        ThemeColor(ColorId.Theme("light_blue_grey_20"), "#919399"),
        ThemeColor(ColorId.Theme("dark_blue_grey_1"), "#000306"),
        ThemeColor(ColorId.Theme("dark_blue_grey_2"), "#05080B"),
        ThemeColor(ColorId.Theme("dark_blue_grey_3"), "#0A0D10"),
        ThemeColor(ColorId.Theme("dark_blue_grey_4"), "#111417"),
        ThemeColor(ColorId.Theme("dark_blue_grey_5"), "#181B1E"),
        ThemeColor(ColorId.Theme("dark_blue_grey_6"), "#1F2225"),
        ThemeColor(ColorId.Theme("dark_blue_grey_7"), "#272A2D"),
        //  ThemeColor(ColorId.Theme("dark_blue_grey_8"), "#313437"),
        ThemeColor(ColorId.Theme("dark_blue_grey_8"), "#313D40"),
        ThemeColor(ColorId.Theme("dark_blue_grey_9"), "#384447"),
        ThemeColor(ColorId.Theme("dark_blue_grey_10"), "#424C4F"),
        ThemeColor(ColorId.Theme("dark_blue_grey_11"), "#484B4E"),
        ThemeColor(ColorId.Theme("dark_blue_grey_12"), "#4F5B5E"),
        ThemeColor(ColorId.Theme("dark_blue_grey_13"), "#556164"),
        ThemeColor(ColorId.Theme("dark_blue_grey_14"), "#5A6669"),
        ThemeColor(ColorId.Theme("dark_blue_grey_15"), "#5F6B6E"),
        ThemeColor(ColorId.Theme("dark_blue_grey_16"), "#657174"),
        ThemeColor(ColorId.Theme("dark_blue_grey_17"), "#6A6D70"),
        ThemeColor(ColorId.Theme("dark_blue_grey_18"), "#6F7B7E"),
        ThemeColor(ColorId.Theme("dark_blue_grey_19"), "#75787B"),
        ThemeColor(ColorId.Theme("dark_blue_grey_20"), "#7A8689"),
        ThemeColor(ColorId.Theme("dark_blue_grey_21"), "#7F8B8E"),
        ThemeColor(ColorId.Theme("dark_blue_grey_22"), "#859194"),
        ThemeColor(ColorId.Theme("dark_blue_grey_23"), "#8A8D90"),
        ThemeColor(ColorId.Theme("dark_blue_grey_24"), "#8F9295"),
        ThemeColor(ColorId.Theme("dark_blue_grey_25"), "#95989B"),
        ThemeColor(ColorId.Theme("dark_grey_1"), "#050505"),
        ThemeColor(ColorId.Theme("dark_grey_2"), "#0A0A0A"),
        ThemeColor(ColorId.Theme("dark_grey_3"), "#111111"),
        ThemeColor(ColorId.Theme("dark_grey_4"), "#181818"),
        ThemeColor(ColorId.Theme("dark_grey_5"), "#1F1F1F"),
        ThemeColor(ColorId.Theme("dark_grey_6"), "#272727"),
        ThemeColor(ColorId.Theme("dark_grey_7"), "#313131"),
        ThemeColor(ColorId.Theme("dark_grey_8"), "#393939"),
        ThemeColor(ColorId.Theme("dark_grey_9"), "#424242"),
        ThemeColor(ColorId.Theme("dark_grey_10"), "#484848"),
        ThemeColor(ColorId.Theme("dark_grey_11"), "#4F4F4F"),
        ThemeColor(ColorId.Theme("dark_grey_12"), "#555555"),
        ThemeColor(ColorId.Theme("dark_grey_13"), "#5A5A5A"),
        ThemeColor(ColorId.Theme("dark_grey_14"), "#5F5F5F"),
        ThemeColor(ColorId.Theme("dark_grey_15"), "#656565"),
        ThemeColor(ColorId.Theme("dark_grey_16"), "#6A6A6A"),
        ThemeColor(ColorId.Theme("dark_grey_17"), "#6F6F6F"),
        ThemeColor(ColorId.Theme("dark_grey_18"), "#757575"),
        ThemeColor(ColorId.Theme("dark_grey_19"), "#7A7A7A"),
        ThemeColor(ColorId.Theme("dark_grey_20"), "#7F7F7F"),
        ThemeColor(ColorId.Theme("dark_grey_21"), "#858585"),
        ThemeColor(ColorId.Theme("dark_grey_22"), "#8A8A8A"),
        ThemeColor(ColorId.Theme("dark_grey_23"), "#8F8F8F"),
        ThemeColor(ColorId.Theme("dark_grey_24"), "#959595"),
        ThemeColor(ColorId.Theme("dark_grey_25"), "#9A9A9A"),
        ThemeColor(ColorId.Theme("dark_grey_26"), "#9F9F9F"),
        //ThemeColor(ColorId.Theme("light_green"), "#79C772"),
        ThemeColor(ColorId.Theme("light_green"), "#84C97A"),
        ThemeColor(ColorId.Theme("green"), "#18C061"),
//        ThemeColor(ColorId.Theme("green"), "#45BD72"),
        ThemeColor(ColorId.Theme("green_tint_1"), "#2FC671"),
        ThemeColor(ColorId.Theme("green_tint_2"), "#46CD81"),
        ThemeColor(ColorId.Theme("green_tint_3"), "#5DD390"),
        ThemeColor(ColorId.Theme("green_tint_4"), "#74D9A0"),
        ThemeColor(ColorId.Theme("green_tint_5"), "#8CE0B0"),
        ThemeColor(ColorId.Theme("green_tint_6"), "#A3E6C0"),
        ThemeColor(ColorId.Theme("green_shade_1"), "#3EAA67"),
        ThemeColor(ColorId.Theme("green_90"), "#E645BD72"),
        ThemeColor(ColorId.Theme("green_80"), "#C445BD72"),
        ThemeColor(ColorId.Theme("green_70"), "#B245BD72"),
        ThemeColor(ColorId.Theme("green_60"), "#9945BD72"),
        ThemeColor(ColorId.Theme("green_50"), "#8045BD72"),
        ThemeColor(ColorId.Theme("red"), "#C01818"),
        ThemeColor(ColorId.Theme("red_tint_1"), "#C62F2F"),
        ThemeColor(ColorId.Theme("red_tint_2"), "#CD4646"),
        ThemeColor(ColorId.Theme("red_tint_3"), "#D35D5D"),
        ThemeColor(ColorId.Theme("red_tint_4"), "#D97474"),
        ThemeColor(ColorId.Theme("orange"), "#C07A18"),
        ThemeColor(ColorId.Theme("orange_tint_1"), "#C6872F"),
        ThemeColor(ColorId.Theme("orange_tint_2"), "#CD9546"),
        ThemeColor(ColorId.Theme("orange_tint_3"), "#D3A25D"),
        ThemeColor(ColorId.Theme("orange_tint_4"), "#D9AF74"),
        //ThemeColor(ColorId.Theme("dark_blue"), "#436686"),
        ThemeColor(ColorId.Theme("dark_blue"), "#246F95"),
        ThemeColor(ColorId.Theme("light_blue"), "#1187B5"),
        ThemeColor(ColorId.Theme("light_blue_90"), "#E61887C0"),
        ThemeColor(ColorId.Theme("light_blue_85"), "#DA1887C0"),
        ThemeColor(ColorId.Theme("light_blue_80"), "#C41887C0"),
        ThemeColor(ColorId.Theme("light_blue_70"), "#B21887C0"),
        ThemeColor(ColorId.Theme("light_blue_60"), "#991887C0"),
        ThemeColor(ColorId.Theme("light_blue_50"), "#801887C0"),
        ThemeColor(ColorId.Theme("light_blue_shade_1"), "#167AAD"),
        ThemeColor(ColorId.Theme("light_blue_shade_2"), "#136C9A"),
        ThemeColor(ColorId.Theme("light_blue_tint_1"), "#2993BC"),
        ThemeColor(ColorId.Theme("light_blue_tint_2"), "#469FCD"),
        ThemeColor(ColorId.Theme("light_blue_tint_3"), "#5DABD3"),
        ThemeColor(ColorId.Theme("light_blue_tint_4"), "#74B7D9"),
        ThemeColor(ColorId.Theme("light_blue_tint_5"), "#8CC3E0"),
        ThemeColor(ColorId.Theme("light_blue_tint_6"), "#A3CFE6"),
        ThemeColor(ColorId.Theme("light_blue_tint_7"), "#BADBEC"),
        ThemeColor(ColorId.Theme("light_blue_tint_8"), "#D1E7F2"),
        ThemeColor(ColorId.Theme("light_blue_tint_9"), "#E8F3F9"),
//        ThemeColor(ColorId.Theme("purple"), "#9161C0"),
//        ThemeColor(ColorId.Theme("purple_90"), "#E69161C0"),
//        ThemeColor(ColorId.Theme("purple_80"), "#C49161C0"),
//        ThemeColor(ColorId.Theme("purple_70"), "#B29161C0"),
//        ThemeColor(ColorId.Theme("purple_60"), "#999161C0"),
//        ThemeColor(ColorId.Theme("purple_50"), "#809161C0"),
        ThemeColor(ColorId.Theme("purple"), "#6818C0"),
        ThemeColor(ColorId.Theme("purple_tint_1"), "#772FC6"),
        ThemeColor(ColorId.Theme("purple_tint_2"), "#8646CD"),
        ThemeColor(ColorId.Theme("purple_tint_3"), "#955DD3"),
        ThemeColor(ColorId.Theme("purple_tint_4"), "#A474D9"),
        ThemeColor(ColorId.Theme("pink"), "#c01877"),
        ThemeColor(ColorId.Theme("pink_tint_1"), "#C62F85"),
        ThemeColor(ColorId.Theme("transparent"), "#00FFFFFF"),
        ThemeColor(ColorId.Theme("transparent_80"), "#33FFFFFF"),
        ThemeColor(ColorId.Theme("transparent_70"), "#4DFFFFFF"),
        ThemeColor(ColorId.Theme("transparent_50"), "#7FFFFFFF"),
        ThemeColor(ColorId.Theme("transparent_30"), "#B3FFFFFF"),
        ThemeColor(ColorId.Theme("transparent_20"), "#CCFFFFFF")
)



val uiColors = UIColors(
        // Toolbar Background
        ColorId.Theme("dark_blue_grey_9"),
        //ColorId.Theme("white"),
        // Toolbar Icons
        ColorId.Theme("white"),
        //ColorId.Theme("dark_blue_grey_14"),
        // Toolbar Title
        ColorId.Theme("white"),
        //ColorId.Theme("dark_blue_grey_14"),
        // Tab Bar Background
        ColorId.Theme("dark_blue_grey_9"),
        //ColorId.Theme("white"),
        // Tab Text Normal
        ColorId.Theme("light_blue_grey_16"),
        // Tab Text Selected
        ColorId.Theme("light_blue_grey_3"),
        //ColorId.Theme("dark_blue_grey_14"),
        // Tab Underline
        ColorId.Theme("white"),
        //ColorId.Theme("dark_blue_grey_14"),
        //ColorId.Theme("light_blue_tint_1"),
        ColorId.Theme("dark_grey_8"),
        ColorId.Theme("light_grey_10"))


//val uiColors = UIColors(
//        ColorId.Theme("white"),
//        ColorId.Theme("dark_grey_10"),
//        ColorId.Theme("dark_grey_10"),
//        ColorId.Theme("white"),
//        ColorId.Theme("dark_grey_16"),
//        ColorId.Theme("dark_grey_10"),
//        ColorId.Theme("dark_grey_16"),
//        ColorId.Theme("dark_grey_8"),
//        ColorId.Theme("light_grey_10"))



val officialThemeLight = Theme(ThemeId.Light, palette, uiColors)


val appUIColors = UIColors(
        ColorId.Theme("white"),
        ColorId.Theme("dark_blue_grey_16"),
        ColorId.Theme("dark_grey_10"),
        ColorId.Theme("white"),
        ColorId.Theme("dark_grey_16"),
        ColorId.Theme("dark_grey_10"),
        ColorId.Theme("dark_grey_16"),
        ColorId.Theme("dark_grey_8"),
        ColorId.Theme("light_grey_10"))


val officialAppThemeLight = Theme(ThemeId.Light, palette, appUIColors)
